

CC	= gcc
CXX	= g++
LD	= g++
RC	= windres

COUT	= -o
LOUT	= -o

OUTPATH	= ../../release/server

CFLAGS	= -c -O2 -Wall -Werror -D_CRT_SECURE_NO_WARNINGS -Ipthread
LDFLAGS	= -Lpthread -lpthread -lws2_32


TARGET	= $(OUTPATH)/server.exe

include objs.mak

all: $(TARGET) test

$(TARGET): $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) $(LOUT)"$@"

test: test.o network.o
	$(LD) test.o network.o $(LDFLAGS) $(LOUT)"$(OUTPATH)/$@"
	
.cpp.o:
	$(CXX) $< $(CFLAGS) $(COUT)$@
	
.c.o:
	$(CC) $< $(CFLAGS) $(COUT)$@
	
%.RES: %.rc
	$(RC) -i $<

include d.mak

.PHONY: clean

clean:
	$(RM) *.o
	$(RM) *.RES
	$(RM) $(OUTPATH)/test.exe

















